routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

	Route::get('wishlist/index', [ 
		'as' => 'wishlist.index', 
		'uses' => 'WishlistController@index']);

	Route::get('wishlist/create', [ 
		'as' => 'wishlist.create', 
		'uses' => 'WishlistController@create']);

	Route::post('wishlist',[ 
		'as' => 'wishlist.store', 
		'uses' => 'WishlistController@store']);

	Route::get('wishlist/{id}/destroy', [
			'uses' 	=> 'WishlistController@destroy',
			'as'	=> 'wishlist.destroy'
		]);
		

	Route::resource('profile','ProfileController');

	Route::resource('search','SearchController');
	Route::get('search/{id}/destroy', [
		'uses' 	=> 'SearchController@destroy',
		'as'	=> 'search.destroy'
	]);



Auth::routes();

Route::get('/home', 'HomeController@index');

resources/views/editProfile.blade.php
@extends('layouts.app')

@section('content')

	<div class="panel-heading">Update Profile of <b>{{ $user->name }}</b></div>
		<div class="panel-body">
			<form class="form-horizontal" method="POST" action="{{ route('profile.update', $user) }}">			
			  
				<input type="hidden" name="_method" value="PUT">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">

				<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
					<label for="name" class="col-md-4 control-label">Name</label>

					<div class="col-md-6">
						<input id="name" type="text" class="form-control" name="name" value="{{ $user->name }}" required autofocus>

						@if ($errors->has('name'))
							<span class="help-block">
								<strong>{{ $errors->first('name') }}</strong>
							</span>
						@endif
					</div>
				</div>

				<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
					<label for="email" class="col-md-4 control-label">E-Mail Address</label>

					<div class="col-md-6">
						<input id="email" type="email" class="form-control" name="email" value="{{ $user->email }}" required>

						@if ($errors->has('email'))
							<span class="help-block">
								<strong>{{ $errors->first('email') }}</strong>
							</span>
						@endif
					</div>
				</div>
	
				<div class="form-group">
					<div class="col-md-6 col-md-offset-4">
						<button type="submit" class="btn btn-primary">
							Update Profile
						</button>
					</div>
				</div>
				
			</form>
		</div>
	</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

	<div class="panel-heading">Home</div>
		<div class="panel-body">
			<form class="form-horizontal" role="form" method="POST" action="{{ route('login') }}">
				{{ csrf_field() }}

				<div class="form-group{{ $errors->has('url') ? ' has-error' : '' }}">
					<label for="text" class="col-md-4 control-label">Inventory Crawler</label>	
				</div>
			</form>
		</div>	
	</div>

@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Login</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('login') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autofocus>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> Remember Me
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Login
                                </button>

                                <a class="btn btn-link" href="{{ route('password.request') }}">
                                    Forgot Your Password?
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection