routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

	Route::get('wishlist/index', [ 
		'as' => 'wishlist.index', 
		'uses' => 'WishlistController@index']);

	Route::get('wishlist/create', [ 
		'as' => 'wishlist.create', 
		'uses' => 'WishlistController@create']);

	Route::post('wishlist',[ 
		'as' => 'wishlist.store', 
		'uses' => 'WishlistController@store']);

	Route::get('wishlist/{id}/destroy', [
			'uses' 	=> 'WishlistController@destroy',
			'as'	=> 'wishlist.destroy'
		]);
		

	Route::resource('profile','ProfileController');

	Route::resource('search','SearchController');
	Route::get('search/{id}/destroy', [
		'uses' 	=> 'SearchController@destroy',
		'as'	=> 'search.destroy'
	]);



Auth::routes();

Route::get('/home', 'HomeController@index');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

   <title>@yield('title', 'Default') | Crawler</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Crawler = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        @yield('title', 'Crawler')
                    </a>
					<a class="navbar-brand" href="{{ route('search.create') }}">
                        Search
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('profile.edit', Auth::user()->id ) }}">Update profile</a>
                                    </li>								
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">         
						@yield('content')						
				</div>
			</div>	
		</div>
	</div>

    <!-- Scripts -->
	<script src="{{ asset('plugins/jquery/js/jquery-3.1.1.js') }}"></script>

    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>